src/Presentation/Projecto.MVC/Controllers/ChatsController.cs
using Projecto.Application.Features.Messages.Queries.GetMessages;
using Projecto.Application.Features.Profile.Queries.GetWithMessageStatus;
using System.Security.Claims;

namespace Projecto.MVC.Controllers
{
    [Authorize]
    public class ChatsController : Controller
    {
        private readonly ISender _sender;

        public ChatsController(ISender sender)
        {
            _sender = sender;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _sender.Send(new GetProfileWithMessageStatusQuery(GetUserId()));
            return View(result.Data);
        }

        public async Task<IActionResult> LoadChat(string recipientUsername)
        {
            var listOfMessageDtos = await _sender.Send(new GetMessagesQuery(GetUserName(), recipientUsername));
            return PartialView("_ChatPartial", listOfMessageDtos);
        }

        private string GetUserName()
        {
            return User.Identity.Name;
        }

        private string GetUserId()
        {
            return User.FindFirstValue(ClaimTypes.NameIdentifier);
        }
    }


}

src/Presentation/Projecto.MVC/Controllers/StoreController.cs
using Projecto.Application.Dtos.ReviewDtos;
using Projecto.Application.Features.Games.Queries.GetByName;
using Projecto.Application.Features.Games.Queries.GetGameWithUserFavouriteStatus;
using Projecto.Application.Features.Reviews.Queries.GetAll;
using Projecto.Application.Features.Reviews.Queries.GetAverageRating;
using Projecto.Application.Features.Reviews.Queries.GetCount;
using System.Security.Claims;

namespace Projecto.MVC.Controllers
{
    public class StoreController : Controller
    {
        private readonly ISender _sender;

        public StoreController(ISender sender)
        {
            _sender = sender;
        }

        public async Task<IActionResult> Index()
        {
            var games = await _sender.Send(new GetGamesQuery());
            return View(games.ToList());
        }

        public async Task<IActionResult> Details(int id, int page = 1)
        {
            string userId = null;

            if (User.Identity.IsAuthenticated)
            {
                userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            }

            var game = await _sender.Send(new GetGameQuery(id));

            if (userId != null)
            {
                game = await _sender.Send(new GetGameWithUserFavouriteStatus(id, userId));
            }

            var paginatedReviewsDto = await _sender.Send(new GetReviewsQuery(id, page));

            var viewModel = new GameDetailsVM
            {
                Game = game,
                NewReview = userId != null ? new ReviewCreateDto(true, "", userId, id) : null,
                PaginatedReviews = new ReviewVM
                {
                    Reviews = paginatedReviewsDto.Reviews,
                    CurrentPage = paginatedReviewsDto.CurrentPage,
                    TotalPages = paginatedReviewsDto.TotalPages,
                },
                AverageRating = await _sender.Send(new GetAverageGameRatingQuery(id)),
                ReviewsCount = await _sender.Send(new GetAllReviewsCount(id))
            };
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Search(string searchTerm)
        {
            var searchResults = await _sender.Send(new GetGameByNameQuery(searchTerm));
            return PartialView("_GameSearchResults", searchResults);
        }
    }
}

src/Presentation/Projecto.MVC/Controllers/WalletController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Projecto.Application.Features.Users.Queries.GetById;
using System.Security.Claims;

namespace Projecto.MVC.Controllers
{
    [Authorize]
    public class WalletController : Controller
    {
        private readonly ISender _sender;
        private readonly UserManager<AppUser> _userManager;
        public WalletController(ISender sender, UserManager<AppUser> userManager)
        {
            _sender = sender;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.FindByIdAsync(GetUserId());
            return View(user);
        }

        private string GetUserId() 
        { 
            return User.FindFirstValue(ClaimTypes.NameIdentifier);
        }
    }
}

src/Presentation/Projecto.MVC/Views/Shared/_ChatPartial.cshtml
@model List<Projecto.Application.Dtos.MessageDtos.MessageDto>
@foreach (var message in Model)
{
    <div class="messages-item @(message.IsSent ? "--friend-message" : "--your-message")">
        @if(!message.IsSent)
        {
            <div class="user-item__avatar">
                <img src="~/images/ProfilePictures/@message.UserProfilePictureName" alt="user">
            </div>
        }
        <div class="messages-item__text">
            @message.Text
        </div>
    </div>
}

src/Presentation/Projecto.MVC/Views/Shared/_GameSearchResults.cshtml
@model IEnumerable<GetGameDto>

<style>
    .search-results-dropdown {
        position: absolute;
        width: 100%;
        max-height: 200px;
        overflow-y: auto;
        background: white;
        border: 1px solid #ccc;
        z-index: 1000;
        list-style: none;
        padding: 0;
        margin: 0;
    }

    .search-result-item {
        display: flex;
        align-items: center;
        padding: 10px;
        border-bottom: 1px solid #eee;
    }

    .search-result-item:hover {
        background: #f9f9f9;
    }

    .search-result-image {
        width: 50px;
        height: 50px;
        margin-right: 10px;
    }

    .search-result-info {
        display: flex;
        flex-direction: column;
        justify-content: center;
    }

    .search-result-title {
        margin: 0;
        font-size: 16px;
        font-weight: bold;
    }

    .search-result-genres {
        margin: 0;
        font-size: 14px;
        color: #888;
    }
</style>

<ul class="search-results-dropdown">
    @foreach (var game in Model)
    {
        <a asp-action="Details" asp-route-id="@game.Id">
        <li class="search-result-item">
                <img src="~/Images/Games/@game.Images.Where(g=>g.IsCoverImage).Select(g=>g.FileName).FirstOrDefault()" alt="@game.Name" class="search-result-image" />
                <div class="search-result-info">
                    <h3 class="search-result-title">@game.Name</h3>
                    <p class="search-result-genres">@string.Join(", ", game.GameGenres.Select(g => g.Genre.Name))</p>
                </div>
        </li>
        </a>

    }
</ul>

src/Presentation/Projecto.MVC/Views/Shared/_Layout.cshtml
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>TeamHost - Join now and play mighty games!</title>
    <meta content="Templines" name="author">
    <meta content="TeamHost" name="description">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="HandheldFriendly" content="true">
    <meta name="format-detection" content="telephone=no">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <link rel="shortcut icon" href="~/assets/img/favicon.png" type="image/x-icon">
    <link rel="stylesheet" href="~/assets/css/libs.min.css">
    <link rel="stylesheet" href="~/assets/css/main.css">
    <link rel="stylesheet" href="~/css/LayoutCustomCSS.css" />
    <link rel="preconnect" href="~/https://fonts.googleapis.com">
    <link rel="preconnect" href="~/https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marcellus&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    @await RenderSectionAsync("ChatStyles", required: false)
    @await RenderSectionAsync("GetCommunityDetailsStyles", required: false)
    @await RenderSectionAsync("AddCommunityStyles", required: false)
    @await RenderSectionAsync("OrderConfirmedStyles",required: false)
    @await RenderSectionAsync("ViewProfileStyles", required: false)
    @await RenderSectionAsync("ViewAllBadgesStyles", required:false)
    @await RenderSectionAsync("EditBadgesStyles", required:false)
    @await RenderSectionAsync("MarketStyles", required:false)
    @await RenderSectionAsync("SellYourItemStyles", required:false)
    @await RenderSectionAsync("ViewMarketItemStyles", required:false)
    @await RenderSectionAsync("HomeStylings", required:false)
    @await RenderSectionAsync("AddCommunityPostStyles", required: false)
</head>

<body class="page-home">

    <!-- Loader-->
    <div id="page-preloader"><span class="spinner border-t_second_b border-t_prim_a"></span></div>
    <!-- Loader end-->

    <div class="page-wrapper">
        <header class="page-header">
            <div class="page-header__inner">
                <div class="page-header__sidebar">
                    <div class="page-header__menu-btn"><button class="menu-btn ico_menu is-active"></button></div>
                    <div class="page-header__logo"><img src="~/assets/img/logo.png" alt="logo"><span class="page-header__logo_text">HollowedKeys</span></div>
                </div>
                <div class="page-header__content">
                    <div class="page-header__search">
                        <div class="search">
                            <div class="search__input"><i class="ico_search"></i><input type="search" name="search" placeholder="Search"></div>
                            <div class="search__btn"><button type="button"><i class="ico_microphone"></i></button></div>
                        </div>
                    </div>
                    <div class="page-header__action">
                        <a asp-controller="Cart" asp-action="Index" class="action-btn">
                            <i class="fas fa-shopping-cart"></i>
                        </a>                        
                        <div class="profile">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <div class="dropdown">
                                    <img src="~/assets/img/profile.png" alt="profile" class="profile-img" onclick="toggleDropdown()">
                                    <div class="dropdown-content" id="dropdownContent">
                                        <a asp-controller="Profile" asp-action="Index">Profile</a>
                                        <a asp-controller="Wallet" asp-action="Index">Wallet</a>
                                        <a href="~/Account/Logout">Logout</a>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="dropdown">
                                    <img src="~/assets/img/profile.png" alt="profile" class="profile-img" onclick="toggleDropdown()">
                                    <div class="dropdown-content" id="dropdownContent">
                                        <a asp-controller="Account" asp-action="Login">Login</a>
                                        <a asp-controller="Account" asp-action="Register">Register</a>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="page-content">
            <aside class="sidebar is-show" id="sidebar">
                <div class="sidebar-box">
                    <ul class="uk-nav">
                        <li class="uk-active"><a asp-controller="Home" asp-action="Index"><i class="ico_home"></i><span>Home</span></a></li>
                        <li class="uk-nav-header">Account</li>
                        <li><a asp-controller="Profile" asp-action="Index"><i class="ico_profile"></i><span>Profile</span></a></li>
                        <li><a asp-controller="Favourites" asp-action="Index"><i class="ico_favourites"></i><span>Favourites</span></a></li>
                        <li><a asp-controller="Chats" asp-action="Index"><i class="ico_chats"></i><span>Chats</span></a></li>
                        <li><a asp-controller="Friends" asp-action="Index"><i class="ico_friends"></i><span>Friends</span></a></li>
                        <li><a asp-controller="Wallet" asp-action="Index"><i class="ico_wallet"></i><span>Wallet</span></a></li>
                        <li class="uk-nav-header">Main</li>
                        <li><a asp-controller="Store" asp-action="Index"><i class="ico_store"></i><span>Store</span></a></li>
                        <li><a asp-controller="Markets" asp-action="Index"><i class="ico_market"></i><span>Market</span></a></li>
                        <li><a asp-controller="Community" asp-action="Index"><i class="ico_community"></i><span>Community</span></a></li>
                    </ul>
                </div>
            </aside>
            @RenderBody()
        </div>
    </div>
    <div class="page-modals">
        <div class="uk-flex-top" id="modal-report" data-uk-modal>
            <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">
                <button class="uk-modal-close-default" type="button" data-uk-close></button>
                <h2 class="uk-modal-title">Report</h2>
                <form class="uk-form-stacked" action="#">
                    <div class="uk-margin">
                        <div class="uk-form-label">Subject</div>
                        <div class="uk-form-controls">
                            <select class="js-select">
                                <option value="">Choose Subject</option>
                                <option value="Subject 1">Subject 1</option>
                                <option value="Subject 2">Subject 2</option>
                                <option value="Subject 3">Subject 3</option>
                            </select>
                        </div>
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label">Details</div>
                        <div class="uk-form-controls"><textarea class="uk-textarea" name="details" placeholder="Try to include all details..."></textarea></div>
                        <div class="uk-form-controls uk-margin-small-top">
                            <div data-uk-form-custom><input type="file"><button class="uk-button uk-button-default" type="button" tabindex="-1"><i class="ico_attach-circle"></i><span>Attach File</span></button></div>
                        </div>
                    </div>
                    <div class="uk-margin">
                        <div class="uk-grid uk-flex-right" data-uk-grid>
                            <div><button class="uk-button uk-button-small uk-button-link">Cancel</button></div>
                            <div><button class="uk-button uk-button-small uk-button-danger">Submit</button></div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="uk-flex-top" id="modal-help" data-uk-modal>
            <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">
                <button class="uk-modal-close-default" type="button" data-uk-close></button>
                <h2 class="uk-modal-title">Help</h2>
                <div class="search">
                    <div class="search__input"><i class="ico_search"></i><input type="search" name="search" placeholder="Search"></div>
                    <div class="search__btn"><button type="button"><i class="ico_microphone"></i></button></div>
                </div>
                <div class="uk-margin-small-left uk-margin-small-bottom uk-margin-medium-top">
                    <h4>Popular Q&A</h4>
                    <ul>
                        <li><img src="~/assets/img/svgico/clipboard-text.svg" alt="icon"><span>How to Upload Your Developed Game</span></li>
                        <li><img src="~/assets/img/svgico/clipboard-text.svg" alt="icon"><span>How to Go Live Stream</span></li>
                        <li><img src="~/assets/img/svgico/clipboard-text.svg" alt="icon"><span>Get in touch with the Creator Support Team</span></li>
                    </ul>
                    <ul>
                        <li><a href="~/#!">browse all articles</a></li>
                        <li><a href="~/#!">Send Feedback</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <script src="~/assets/js/libs.js"></script>
    <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("ProfileButtonScript", required:false)
    @await RenderSectionAsync("ChatScripts", required: false)
    @await RenderSectionAsync("StoreDetailsScripts", required: false)
    @await RenderSectionAsync("GetCommunityDetailsScripts", required: false)
    @await RenderSectionAsync("OrderConfirmedScripts", required:false)
    @await RenderSectionAsync("EditBadgesScripts", required:false)
    @await RenderSectionAsync("CommunityPageScripts", required: false)
    @await RenderSectionAsync("SellYourItemScripts", required:false)
    @await RenderSectionAsync("HomeScripts", required:false)
    @await RenderSectionAsync("AddCommunityPostScripts", required:false)
    @await RenderSectionAsync("AddCommunityPostScripts2", required: false)
    <script>
        function toggleDropdown() {
            var dropdownContent = document.getElementById("dropdownContent");
            dropdownContent.classList.toggle("show");
        }

        window.onclick = function (event) {
            if (!event.target.matches('.profile-img')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                for (var i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>
</body>

</html>

src/Presentation/Projecto.MVC/Views/Shared/_ReviewsPartial.cshtml
@model ReviewVM

<div class="card">
    <div class="card-body">
        @foreach (var review in Model.Reviews)
        {
            <div class="media mb-3">
                <img class="mr-3 rounded-circle" src="~/images/ProfilePictures/@review.User.ProfilePicture.FileName" alt="user" width="64" height="64">
                <div class="media-body">
                    <h5 class="mt-0">@review.User.UserName</h5>
                    <small class="text-muted">@review.CreatedAt.ToString("g")</small>
                    @if (@review.IsLiked)
                    {
                        <p><i class="fa fa-thumbs-up text-success" aria-hidden="true"></i> Recommended</p>
                    }
                    else
                    {
                        <p><i class="fa fa-thumbs-down text-danger" aria-hidden="true"></i> Not recommended</p>
                    }
                    <p>@review.Comment</p>
                </div>
            </div>
            <hr>
        }
    </div>
</div>